`sdl2/Nintendo Switch Pro Controller.cfg` renamed to `Nintendo Co.,Ltd. Pro Controller.cfg renamed to sdl2/Nintendo Switch Pro Controller.cfg to Nintendo Co.,Ltd. Pro Controller.cfg`
libretro/retroarch-joypad-autoconfig pull request #1156
Opened 2024-07-29 18:09 UTC by davidhedlund

* Retroarch generates `Nintendo Co., Ltd. Pro Controller.cfg` not `Nintendo Switch Pro Controller.cfg`
* RetroArch generates `input_device = "Nintendo Co., Ltd. Pro Controller"` not `input_device = "Nintendo Switch Pro Controller"`

2024-07-29 23:34 UTC, davidhedlund commented
Please, let's quickly solve this issue first:
* https://github.com/libretro/retroarch-joypad-autoconfig/issues/1157

2024-09-28 18:24 UTC, RobLoach requested changes

2024-09-28 18:24 UTC, RobLoach commented on sdl2/Nintendo Switch Pro Controller.cfg
> -input_a_btn = "1"
Looks like we're flipping A/B. RetroArch uses A for right face button, and B for the bottom face button. Is this change correct? You can see a visual of it over at:
https://www.lakka.tv/doc/Input-settings/

2024-10-03 04:55 UTC, davidhedlund commented on sdl2/Nintendo Switch Pro Controller.cfg
> -input_a_btn = "1"
This is correct (just generated a test autoconfig to verify it for you), it's generated by RetroArch 1.19.1.

I am confident that every single binding in all pull requests is 100% correct. The only manual additions I've made are for the analog L2/R2 buttons on PlayStation controllers, specifically for drivers that didn't generate them in RetroArch. I maintain a detailed spreadsheet that tracks all controllers, drivers, manual bindings, and bug reports.

All autoconfigurations I've uploaded since the release of RetroArch 1.19.1 have been generated from that version. I've tested every autoconfig 2-3 times.

I'm certain that all pull requests can be approved without the need to merge them and potentially review everything again. I would prefer not to spend additional time on this, as it has already taken a significant amount of effort to reach this point.

2024-10-03 04:55 UTC, davidhedlund commented on sdl2/Nintendo Switch Pro Controller.cfg
> -input_a_btn = "1"
> Looks like we're flipping A/B. RetroArch uses A for right face button, and B for the bottom face button.

Since which RetroArch version (please give me a reference link if possible)?

* My Android autoconfigs have been generated with RetroArch 1.17.0 due a bug that prevents me from installing the current version (1.19.1). I submitted that bug here: https://github.com/libretro/RetroArch/issues/17014

2025-07-19 21:11 UTC, merged

2025-07-20 01:16 UTC, DJtheMan2101 commented
@davidhedlund The mappings are good, but the labels for L2 and R2 are messed up. L2 and R2 are considered axes, but the labels are for L2 and R2 buttons, so they do not show up in RetroArch.

2025-07-20 01:27 UTC, davidhedlund commented
> @davidhedlund The mappings are good, but the labels for L2 and R2 are messed up. L2 and R2 are considered axes, but the labels are for L2 and R2 buttons, so they do not show up in RetroArch.

I just submitted a PR:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1248