Update Sony-PlayStation4-DualShock4v2-Controller.cfg
libretro/retroarch-joypad-autoconfig pull request #1168
Opened 2024-08-06 08:24 UTC by davidhedlund

input_device_display_name = "Sony DualShock 4 v2 Controller"

2024-09-28 17:59 UTC, RobLoach requested changes

2024-09-28 17:59 UTC, RobLoach commented on udev/Sony DualShock 4 Controller.cfg
> +input_product_id_alt1 = "2508"
Looks like this vendor/product ID pair is covered in `udev/Sony_PlayStation4_Dualshock4_500-Million_Limited_Edition.cfg`. We may be able to delete that file if we bring this `alt` in. Mind making sure the button combinations are the same?

2024-09-28 17:59 UTC, RobLoach commented on udev/Sony DualShock 4 Controller.cfg
> +input_product_id_alt2 = "1476"
This combination may be covered in the following configs...
```
udev/Sony-PlayStation4-DualShock4-Controller.cfg
udev/Sony-PlayStation4-DualShock4-Controller-Bluetooth.cfg
```

While I appreciate the merging, I'm worried about overriding those existing configs.

2024-10-02 21:37 UTC, davidhedlund commented on udev/Sony DualShock 4 Controller.cfg
> +input_product_id_alt1 = "2508"
Done:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1168/commits/479c3413c6b40cb76e7596ba4cddc3071efb3b2a
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1168/commits/d6d6bc1562aed533d069e4337c358daf9a490ab5

Thank you!

2024-10-02 22:07 UTC, davidhedlund commented on udev/Sony DualShock 4 Controller.cfg
> +input_product_id_alt2 = "1476"
Good catch!

udev utilize VID/PID so I removed `udev/Sony-PlayStation4-DualShock4-Controller-Bluetooth.cfg`: 

Notes about `udev/Sony-PlayStation4-DualShock4-Controller-Bluetooth.cfg`:
* Is was outdated, it does not contain analog L2/R2 binding.
* Minor detail: `input_device_alt1 = "Wireless Controller"` is the Bluetooth name, it was already added to this PR

Do not worry that any configs will be broken. I can assure you 100% that everything will be fine!

2025-07-19 21:12 UTC, merged