Create PS4 Controller (v2).cfg
libretro/retroarch-joypad-autoconfig pull request #1170
Opened 2024-08-06 08:37 UTC by davidhedlund

2024-08-06 08:40 UTC, davidhedlund commented
* Rename to just "PS4 Controller (v2).cfg" later when "PS4 Controller.cfg" has been renamed to "PS4 Controller (v1).cfg" -- this is the most recent version of the controller.

2024-09-28 17:37 UTC, RobLoach requested changes
Conflicts. And could you merge this with the other PS4 Controller-related configs? It's quite different to review them all when they're all related to the same thing.

2024-10-02 21:15 UTC, davidhedlund commented
> Conflicts. And could you merge this with the other PS4 Controller-related configs? It's quite different to review them all when they're all related to the same thing.

It is ok if you merge https://github.com/libretro/retroarch-joypad-autoconfig/pull/1188 for me

2024-10-03 05:36 UTC, davidhedlund commented
> Conflicts. And could you merge this with the other PS4 Controller-related configs? It's quite different to review them all when they're all related to the same thing.

I merged:
*  https://github.com/libretro/retroarch-joypad-autoconfig/pull/1188
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1190

2025-07-19 21:11 UTC, merged