linuxraw: Create Nintendo Co., Ltd. Pro Controller.cfg
libretro/retroarch-joypad-autoconfig pull request #1174
Opened 2024-08-10 15:12 UTC by davidhedlund

2024-08-15 22:54 UTC, RobLoach requested changes

2024-08-15 22:54 UTC, RobLoach commented on linuxraw/Nintendo Co., Ltd. Pro Controller.cfg
> +input_device = "Nintendo Co., Ltd. Pro Controller"
Mind adding the vendor and product ids?

2024-08-18 00:23 UTC, davidhedlund commented on linuxraw/Nintendo Co., Ltd. Pro Controller.cfg
> +input_device = "Nintendo Co., Ltd. Pro Controller"
The linuxraw driver does not utilize the Vendor ID and Product ID. This is thoroughly explained in the documentation available at https://docs.libretro.com/guides/controller-autoconfiguration/.

Please review the entire guide (https://docs.libretro.com/guides/controller-autoconfiguration/), as I have [invested considerable time in enhancing it](https://github.com/libretro/docs/commits/master/docs/guides/controller-autoconfiguration.md?author=davidhedlund).

2024-08-26 05:12 UTC, davidhedlund commented
I will create a group of pull requests that include both HID and non-HID auto-configurations for linuxraw.

2024-09-04 19:02 UTC, davidhedlund commented on linuxraw/Nintendo Co., Ltd. Pro Controller.cfg
> +input_device = "Nintendo Co., Ltd. Pro Controller"
They are not generated or utilized by this controller driver

2024-09-17 04:51 UTC, merged