Update PS4 Controller (v1).cfg
libretro/retroarch-joypad-autoconfig pull request #1188
Opened 2024-09-04 22:17 UTC by davidhedlund

restored `input_device = "PS4 Controller"`, see https://github.com/libretro/docs/pull/984

2024-09-28 17:38 UTC, RobLoach requested changes

2024-09-28 17:38 UTC, RobLoach commented on sdl2/PS4 Controller (v1).cfg
> -input_product_id = "1476"
If we merge both the PRs, we then are missing a config with this vendor/product ID pair. Would you mind merging the related PRs together so it's easier to review the diff? Thanks.

2024-10-02 19:55 UTC, davidhedlund commented on sdl2/PS4 Controller (v1).cfg
> -input_product_id = "1476"
I merged the v1 VID/PID to https://github.com/libretro/retroarch-joypad-autoconfig/pull/1170/files
```
input_vendor_id = "1356"
input_product_id = "1476"
```

I attempted to merge the pull requests but was unsuccessful because the web interface in my repository lacked the necessary tools to do so. However, only two pull requests are affected by this issue, so please bear with me.

2024-10-02 21:16 UTC, davidhedlund commented on sdl2/PS4 Controller (v1).cfg
> -input_product_id = "1476"
It is ok i you merge this PR for me, but do not merge all PRs.

2024-10-03 05:33 UTC, davidhedlund commented
Merged: https://github.com/libretro/retroarch-joypad-autoconfig/pull/1170/commits/f5d971642af071544d3bf14737c3693e56efb0aa

2024-10-03 05:33 UTC, closed without merging