[READY] udev: Update and rename Microsoft_X-Box_pad_v2_US.cfg to Microsoft X-Box pad (US).cfg -- Merged v1 and v2
libretro/retroarch-joypad-autoconfig pull request #1191
Opened 2024-09-13 01:06 UTC by davidhedlund

* https://github.com/libretro/RetroArch/pull/16990

2024-09-17 04:17 UTC, RobLoach requested changes

2024-09-17 04:17 UTC, RobLoach commented on udev/Microsoft_X-Box_pad_v1_US.cfg
> -input_product_id = "514"
You'll wantt to retain the vendor_id and product_ids in the new file...

```
input_vendor_id_alt1 = "1118"
input_product_id_alt1 = "514"
```

2024-10-03 04:58 UTC, davidhedlund reviewed
added
```
input_vendor_id_alt1 = "1118"
input_product_id_alt1 = "514"
```

Thanks fob

2025-04-29 04:02 UTC, RobLoach requested changes

2025-04-29 04:02 UTC, RobLoach commented on udev/Microsoft X-Box pad (US).cfg
> -# Hex vid:pid = 045e:0289 -> Decimal vid:pid = 1118:649
Mind if we keep this documentation? Can be helpful for others.

2025-07-19 21:10 UTC, merged