Added gamepad profiles for STK-7039RG
libretro/retroarch-joypad-autoconfig pull request #1210
Opened 2024-12-25 19:52 UTC by cjdg

Gamepad profiles related with the STK-7039RG

2024-12-25 21:00 UTC, cjdg commented
I added a small documentation for common profiles for the Saitek STK-7039RGB controller

2024-12-31 06:40 UTC, RobLoach requested changes
Thank you so much. While we would usually prefer to handle the permissions in a different Pull Request, I think it's fine to have them here. Thanks for the clean up.

Mind adding some of the button labels? Then they'll appear cleanly in the UI.

2024-12-31 06:40 UTC, RobLoach commented on udev/7039RG.cfg
> +input_r_y_minus_axis = "-3"
Would you mind added the button labels here too?

2024-12-31 06:40 UTC, RobLoach commented on udev/Afterglow Prismatic Wired Controller.cfg
> +input_r_y_minus_axis = "-4"
Button labels :pray:

2024-12-31 06:40 UTC, RobLoach commented on udev/SHANWAN Android Gamepad.cfg
> +input_r_x_minus_axis = "-2"
Button labels would help here :pray:

2024-12-31 06:40 UTC, RobLoach commented on udev/ZhiXu Gamepad.cfg
> +input_r_y_minus_axis = "-3"
Mind some button labels?

2024-12-31 06:40 UTC, merged

2024-12-31 06:41 UTC, RobLoach commented
Actually, going to merge this for now. Would you mind adding the button labels in?