Add autoconfig for HOLTEK's Twin Shock
libretro/retroarch-joypad-autoconfig pull request #583
Opened 2019-09-30 19:51 UTC by requeijaum

Another DualShock rip-off for PC.
Originally in Brazilian marked since 2004 under "Clone" OEM branding.
I need to test the analog mode, though.

----

The analog mode PCB contact is broken. I might solder a push-button later.

The analog axis from left and right thumb are simple guesses from my usage with a Windows driver... long time ago.

2019-09-30 22:07 UTC, hizzlekizzle commented
hey, thanks for this. is there a reason the button labels are all commented out?

2019-10-07 06:39 UTC, requeijaum commented
I preferred not to mess with the buttons labels since users can make a mess of it.
That's all because of the buttons markings wearing out and there is an offset of "1" between a marking and the real button (eg. button 0 is marked as 1).

2019-10-07 15:09 UTC, offalynne commented
the 0/1 difference isn’t a mistake; windows enumerates buttons in a “human readable” way in user-facing interfaces, ie 1-n instead of 0-n.

2021-01-23 21:06 UTC, RobLoach requested changes

2021-01-23 21:06 UTC, RobLoach commented on HOLTEK_Twin-Shock.cfg
> +#input_select_btn_label = "Select"
No need to comment these out, as mentioned above :wink:

2021-01-24 06:18 UTC, RobLoach commented on HOLTEK_Twin-Shock.cfg
> +input_device = "HOLTEK Twin Shock"
Would be good to have a `input_device_display_name` too.

2021-03-13 22:05 UTC, offalynne commented
@requeijaum how did you get the vendor and product fields here? did you author the cfg manually ? the autoconfig format uses decimal and these look to be hex values

2021-03-14 04:09 UTC, requeijaum commented
I used macOS System Profiler, Linux's lsusb and Windows 10's Device Manager.
VID and PID are hex values. I didn't know about autoconfig's decimal format.


Em sáb., 13 de mar. de 2021 às 19:05, alynne o. ***@***.***>
escreveu:

> @requeijaum <https://github.com/requeijaum> how did you get the vendor
> and product fields here? did you author the cfg manually ? the autoconfig
> format uses decimal and these look to be hex values
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/libretro/retroarch-joypad-autoconfig/pull/583#issuecomment-798792856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKORW35ALQLZESAYLMP4Q3TDPHTHANCNFSM4I373VZA>
> .
>

2021-03-14 04:10 UTC, requeijaum commented
Hey, @RobLoach 
What do you think? Are the USB VID and PID values OK ?
I will also approve your requested changes tomorrow.

2021-03-14 05:43 UTC, offalynne commented
assuming rob doesn’t have the hardware on hand to check. they are indeed supposed to be decimal, check other configs to compare

2021-05-24 17:29 UTC, merged

2021-05-24 17:29 UTC, RobLoach commented
Merging this, going to fix it up after the merge.