HID: add HORI mini wired PS4 USB controller
libretro/retroarch-joypad-autoconfig pull request #683
Opened 2020-09-04 12:03 UTC by Kert

Related to https://github.com/libretro/RetroArch/pull/11280

2021-01-23 18:58 UTC, RobLoach requested changes
Thanks a lot! Would you mind adding a comment at the top of the config with a link to the hardware?

2021-01-24 03:38 UTC, Kert commented
@RobLoach Would this be fine? https://stores.horiusa.com/wired-mini-gamepad-black/. Does // work there?
Also the other configs don't have any links included

2021-01-24 05:18 UTC, RobLoach commented
That URL is perfect. You'll want a comment about the device, along with a `input_device_display_name` so that the notification looks pretty when you plug it in.......

Example: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/3H%20Dual%20Arcade.cfg

2021-01-24 06:08 UTC, RobLoach commented on hid/HORI_mini_wired_ps4.cfg
> +input_device = "HORI mini wired PS4"
``` suggestion
# HORI Wired Mini Gamepad for PS4
# https://stores.horiusa.com/wired-mini-gamepad-black/
input_device = "HORI mini wired PS4"
input_device_display_name = "HORI PS4 Mini Wired Gamepad"
```

2021-01-24 06:09 UTC, merged