(XINPUT) XBOX 360 and Generic XInput touch-up
libretro/retroarch-joypad-autoconfig pull request #688
Opened 2020-09-11 16:49 UTC by sonninnos

- Added proper official XBOX 360 profile to prevent fallback usage
- Removed obsolete "(User X)" profiles
- Renamed "Generic 360 Pad" to "Generic XInput Controller"
- Reorganized btns and labels

With these changes DualShock3 via ScpToolkit will be seen as "Generic XInput Controller" and regular X360 controllers as "XBOX 360 Controller", matching the XBOX One profile display name.

2020-09-19 15:17 UTC, andshrew commented
Is your product ID (673) for the 360 controller definitely correct? My official wired controller has product ID 654 which you have in the `Generic XInput Controller` config here. 654 is also the ID which is already used in the dinput config (XBOX_360.cfg)[https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/dinput/XBOX_360.cfg]. 

If the user 2,3,4 configs are no longer required it may be better to just have a single config for this rather than trying to differentiate between official and generic 360 controller, especially given the number of controllers which use these IDs to appear as 360 controllers.

2020-09-19 15:50 UTC, sonninnos commented
Ah, that explains why ScpToolkit controller is seen as different product_id. I only have actual wireless ones to test with.

So perhaps the generic should be renamed as "Wired" and this new one "Wireless" then.

Single config indeed won't cut it, since the reason for these changes was because the wireless ones went into fallback mode due to the recent changes in RA that require product/vendor matches.

Yes, those extra 2,3,4 configs did nothing. The correct new config was picked up fine for both 2 identical wireless ones, but there is an unrelated issue in RA when mixing wired and wireless: If wireless is #1 and wired #2, the controller labels will switch around, so that the first controller will be seen as the second (both in the init widget and in remap index), but they do work in the correct order.

2020-09-19 16:07 UTC, andshrew commented
> So perhaps the generic should be renamed as "Wired" and this new one "Wireless" then.

I think that sounds like a good idea.

2020-09-19 17:02 UTC, sonninnos commented
Hopefully that sorts it out.

2021-01-23 18:55 UTC, RobLoach requested changes
Looks good. Thanks! Just a quick update to use `Xbox` instead of `XBOX`.

2021-01-23 18:55 UTC, RobLoach commented on xinput/XBOX 360 Wired Controller.cfg
> +input_device_display_name = "XBOX 360 Wired Controller"
``` suggestion
input_device_display_name = "Xbox 360 Wired Controller"
```

2021-01-23 18:55 UTC, RobLoach commented on xinput/XBOX 360 Wireless Controller.cfg
> +input_device_display_name = "XBOX 360 Wireless Controller"
``` suggestion
input_device_display_name = "Xbox 360 Wireless Controller"
```

2021-01-23 19:44 UTC, sonninnos commented
Okey dokey!

2021-01-23 21:10 UTC, merged