8BitDo PC Engine Pad added
libretro/retroarch-joypad-autoconfig pull request #799
Opened 2021-11-04 20:29 UTC by fmaida

2021-11-04 21:28 UTC, offalynne commented
@fmaida hi, would you please consider authoring a map for the SDL Community gamepad data repo ? we're missing data on Mac https://github.com/gabomdq/SDL_GameControllerDB

thanks :-)

2021-11-08 01:29 UTC, RobLoach requested changes
Thanks, mind adding some additional fields to this, as well as labels and documenation? Some good example:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/hid/8BitDo_N30_Pro2_USB.cfg

2021-11-08 09:42 UTC, fmaida commented
> Thanks, mind adding some additional fields to this, as well as labels and documenation? Some good example: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/hid/8BitDo_N30_Pro2_USB.cfg

Whoops, sorry. I'll do that in the next few days.

2022-05-26 22:16 UTC, offalynne commented
@RobLoach 

```
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_select_btn_label = "Select"
input_start_btn_label = "Run"
input_a_btn_label = "I"
input_b_btn_label = "II"
```

should do it.

@fmaida if you could grab me the GUID for SDL with the following tool I would appreciate it: https://www.generalarcade.com/gamepadtool/

2022-06-04 09:17 UTC, fmaida commented
I'm not sure if I did it properly, anyway:

```030000000d0f00003801000008010000```

```030000000d0f00003801000008010000,PCEngine PAD,platform:Mac OS X,a:b1,b:b2,back:b8,start:b9,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,```

2022-06-04 18:35 UTC, offalynne commented
Thank you so much!

2022-06-05 04:02 UTC, RobLoach commented on hid/PCEngine PAD.cfg
> +input_gun_offscreen_shot_mbtn = "2"
``` suggestion
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_select_btn_label = "Select"
input_start_btn_label = "Run"
input_a_btn_label = "I"
input_b_btn_label = "II"
```

2022-06-05 04:04 UTC, merged